module com.search {
    requires javafx.base;
    requires animatefx;
    requires javafx.graphics;
    requires eu.iamgio.animated;
    requires org.controlsfx.controls;
    requires com.dlsc.formsfx;
    requires net.synedra.validatorfx;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.bootstrapfx.core;
    requires eu.hansolo.tilesfx;
    requires com.almasb.fxgl.all;
    requires MaterialFX;
    requires static lombok;
    requires org.kordamp.ikonli.antdesignicons;
    requires org.kordamp.ikonli.core;
    requires spring.beans;
    requires okhttp3;
    requires org.apache.commons.io;
    requires com.alibaba.fastjson2;
    requires java.logging;
    requires org.slf4j;
    requires spring.core;
    requires jdk.httpserver;
    requires javafx.controls;
    requires javafx.web;
    requires javafx.media;
    requires javafx.swing;
    opens com.search to javafx.fxml;
    exports com.search;
    exports com.search.entry;
}